### ISSUE TITLE
Link on the header to return to the ranking page

### ISSUE THREAD

**Issue by gsandino** [oscarpg/ncomplo-euro2016#3]
When you are taking a look at your bets and then you want to go back to the ranking page, now its needed to go to the bottom of the page, what is not  very user friendly.

It could be great to have a link in the header (for example making the NCompló a link as many pages do).

**Comment by oscarpg** [comment]
We are currently reviewing your issue related to add a link in the header of the page and we will get back to you when we have more information.

Best Regards,

**Comment by oscarpg** [comment]
It will be released with the next update.
